### ISSUE TITLE
No ticket reply, wrong prices

### ISSUE THREAD

**Issue by m4aax16** [g2a-official/integration-api-client#8]
Hello, I run a platform that uses your API and my clients get wrong prices.

I get over the API a minPrice of 4.77 € from productID 10000046641004 as API response.
I always end up paying 6.30 €.

The minPrice is the only price which I'm able to retreive from your github package by function $product->getMinPrice();
( https://github.com/g2a-official/integration-api-client )
So I assume that the minPrice always has to be paid.
When I start a CURL request the server response two diffrent prices.
The "minPrice" and "retail_min_price".

The "retail_min_price" is always charged.

This is a B2B business, whereby taxes should be excluded.
That's what applies to all transactions.

In the past, the minPrice was always paid over the G2A API.
In addition, I have no way of viewing the retail min_price via your package.

At 08.11.2020 I run into another price conflict.

Before the retail_min_price was always higher, now the minPrice is higher at product ID : 10000084314003
Actually retail_min_price : 5.28€
Actually minPrice : 6€
My system tried to place the order with a price of 5.28€
The order was rejected.Then I changed the price in the database to 6€ and my system tried to order from you for 6€ with success and a bug. The order has been paid for. I got the product at a price of 5.28 €, although 6 € were requested.

I don't get an sensible  answer from you via the ticket system.
As with all my customers, the only message that comes in is "we'll take care of it".

**Comment by truchosky** [comment]
g2a sucks, support sucks, api team sucks

**Comment by m4aax16** [comment]
@truchosky My program has already generated over  100,000 € in sales. Fortunately, there are other supplier connections. Therefore my customers can switch to other suppliers very quickly. And G2A foregoes all sales because of the API bug. By the way, my customers are online shop operators.  Thus G2A does without the connection of hundreds of online shops

**Comment by truchosky** [comment]
other suppliers like kinguin or cws can't compite with g2a prices, unfortunately, or even with products, if there is some alternative to g2a I will use it cause they don't care about customers

**Comment by m4aax16** [comment]
@truchosky Fixed
